<h1>Livros</h1>

<p><a href="<?php echo $this->url('livraria-admin', ['controller' => 'livros', 'action' => 'new']) ?>" class="btn btn-link"><i class="glyphicon glyphicon-plus"></i> Novo</a></p>

<table class="table table-striped table-condensed">
    <thead>
    <tr>
        <th width="5%" class="text-center">ID</th>
        <th>Nome</th>
        <th>Categoria</th>
        <th>Autor</th>
        <th>ISBN</th>
        <th>Valor</th>
        <th width="8%" class="text-center">Ação</th>
    </tr>
    </thead>

    <tbody>
    <?php foreach($this->data as $categoria) : ?>
        <tr>
            <td class="text-center"><?= $categoria->getId(); ?></td>
            <td><?= $categoria->getNome() ?></td>
            <td><?= $categoria->getCategoria() ?></td>
            <td><?= $categoria->getAutor() ?></td>
            <td><?= $categoria->getIsbn() ?></td>
            <td><?= $categoria->getValor() ?></td>
            <td class="text-center">
                <div class="btn-group btn-group-xs" role="group" aria-label="...">
                    <a href="<?php echo $this->url('livraria-admin-interna', ['controller' => 'livros', 'action' => 'edit', 'id' => $categoria->getID()]) ?>" class="btn btn-primary"><i class="glyphicon glyphicon-pencil"></i> </a>
                    <a href="<?php echo $this->url('livraria-admin-interna', ['controller' => 'livros', 'action' => 'delete', 'id' => $categoria->getID()]) ?>" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i> </a>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>

</table>
<br>
<?php echo $this->paginationControl($this->data, 'Sliding', 'paginator'); ?>
