<h1>Novo Livro</h1>

<?php
$form = $this->form;

$form->setAttribute('action', $this->url('livraria-admin', ['controller'=>'livros', 'action'=>'new']));

$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome')).'<br>';
echo $this->formRow($form->get('categoria')).'<br>';
echo $this->formRow($form->get('autor')).'<br>';
echo $this->formRow($form->get('valor')).'<br>';
echo $this->formRow($form->get('isbn')).'<br>';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

?>