<h1>Editando Categoria</h1>

<?php
$form = $this->form;

$form->setAttribute('action', $this->url('livraria-admin-interna', ['controller'=>'categorias', 'action'=>'edit']));

$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome'))."<br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

?>