<?php
$urlPattern = $_SERVER['REQUEST_URI'];
$formatUrl = function ($page) use ($urlPattern){
    if(!preg_match('/page/', $urlPattern))
        return $urlPattern . "/page/" . $page;
    else
        return preg_replace('/\d/', $page, $urlPattern);
}
?>
<center>
    <?php if ($this->pageCount): ?>
        <div class="paginationControl">
            <div class="hidden"><?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?> de <?php echo $this->totalItemCount; ?><br></div>

            <ul class="pagination">
            <!-- First page link -->
            <?php if (isset($this->previous)): ?>
                <li><a href="<?php echo $formatUrl($this->first); ?>">
                        &laquo;
                </a></li>
            <?php else: ?>
                <li class="disabled"><span>&laquo;</span></li>
            <?php endif; ?>

            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li><a href="<?php echo $formatUrl($this->previous); ?>">
                    Anterior
                </a></li>
            <?php else: ?>
                <li class="disabled"><span>Anterior</span></li>
            <?php endif; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li><a href="<?php echo $formatUrl($this->next); ?>">
                    Próximo
                </a></li>
            <?php else: ?>
                <li class="disabled"><span>Próximo</span></li>
            <?php endif; ?>

            <!-- Last page link -->
            <?php if (isset($this->next)): ?>
                <li><a href="<?php echo $formatUrl($this->last); ?>">
                        &raquo;
                </a></li>
            <?php else: ?>
                <li class="disabled"><span class="disabled">&raquo;</span></li>
            <?php endif; ?>
            </ul>
        </div>
    <?php endif; ?>
</center>
